#!/bin/sh

dialog --title "Confirm" --yesno "Are you willing to take part?" 9 18
if [ $? != 0 ] ; then
	dialog --infobox "Thank you anyway" 5 20
	sleep 2
	dialog --clear
	exit 0
else
	dialog --title "Questionaire" --inputbox "Please enter your name" 9 30 2>_1.txt
	Q_NAME=$(cat _1.txt)
	echo $Q_NAME
fi
