#!/bin/sh

yes_or_no(){
	echo "Is your name $* ?"
	while true
	do
	echo "enter yes or no"
	read x
	case "$x" in
		y | yes) return 0;;
		n | no) return 1;;
		*) echo "answer yes or no"
	esac
	done
}

echo "original param are $*"

if yes_or_no "$1"
then
	echo "Hi $1"
else
	echo "nvm"
fi

exit 0
