#!/bin/sh

trap 'rm -f /tmp/my_tmp_file_$$' INT
echo creating file /tmp/my_tmp_file_$$
date > /tmp/my_tmp_file_$$

echo "press ctrl-c to interrupt"
while [ -f /tmp/my_tmp_file_$$ ]; do
	echo file exists
	sleep 1
done
echo the file no longer exist

trap 'rm -f /tmp/my_tmp_file_$$' INT
echo creating file /tmp/my_tmp_file_$$
date > /tmp/my_tmp_file_$$

echo "press ctrl-c to interrupt"
while [ -f /tmp/my_tmp_file_$$ ]; do
	echo file exists
	sleep 1
done
echo the file no longer exist 2

trap INT
echo creating file /tmp/my_tmp_file_$$
date > /tmp/my_tmp_file_$$

echo "press ctrl-c to interrupt"
while [ -f /tmp/my_tmp_file_$$ ]; do
	echo file exists
	sleep 1
done

echo we never get here
exit 0
